name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  barcode: ^2.2.9
  data_table_2: ^2.7.2
  docx_template: ^0.4.0

  excel: ^4.0.6
  file_picker: ^10.3.7
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_typeahead: ^5.2.0
  http: ^1.6.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  sqflite_common_ffi: ^2.4.0
  syncfusion_flutter_xlsio: ^29.2.11
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/sql/units.sql
    - assets/sql/tabaeia.sql

fonts:
    - family: Cairo  # الخط الجديد
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf # لو متوفر عندك

    - family: NotoNaskh
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
        - asset: assets/fonts/NotoNaskhArabic-Bold.ttf
    
